### ISSUE TITLE
Active vs. hyptic voice

### ISSUE THREAD

**Issue by jkshapiro** [gctools-outilsgc/design-system-code#112]
One of the pieces of advice on the page https://design.gccollab.ca/content/content-guidelines is to "Use the active voice", because "the active voice is closer to the way we talk, and is more dynamic and easy to read".

This assertion is incorrect. We use the direct and vigorous hyptic voice, as the linguistic blog Language Log [puts it](http://itre.cis.upenn.edu/~myl/languagelog/archives/003417.html), just about all the time. For instance, take the following sentence on the page under discussion: "Nominalizations are abstract nouns formed from verbs." Would that read better if converted to the active voice ("Nominalizations are abstract nouns that people formed from verbs")? No: it's excellent just the way it is.

When the agent is relevant, the active voice is great. But when the agent is not relevant (e.g. "trespassers will be prosecuted", "a 15% gratuity will be added to your bill", "it's considered polite to say thank you"), the active voice introduces an unnecessary distraction, and I think that the current wording overlooks that distinction.

Even something like "Prefer the active voice" (rather than "Use...") would be better, with a note about the relevance of agency.

Oh, also the page heading includes the phrase "reading level", but there's nothing on the page about reading levels.

**Comment by s-duffey** [comment]
Thanks for the note @jkshapiro ! Good points here. We'll add this to our workplan for the next sprint.

**Comment by s-duffey** [comment]
Changes made in latest pull request. Will be live after next deployment of the site.

**Comment by jkshapiro** [comment]
Thanks for replacing "use" with "prefer". I think some further rewriting would help: the text still contains the incorrect assertion that "The active voice is closer to the way we talk, and is more dynamic and easy to read". If you listen to actual, dynamic, conversation, you'll notice a lot of hyptic voice being used.

The assertion that "things don't happen to people, people DO things" is also incorrect. Things happen to people every day.

Some more examples, if needed:

Hyptic:
I was held up by traffic
Active:
* Traffic held me up

Hyptic:
Swimming prohibited after 9 pm
Active:
* Beach authority prohibits swimming after 9 pm

Hyptic:
Parliament was dissolved
Active:
* The governor general dissolved Parliament
