### ISSUE TITLE
Add more information to Colour documentation and how to apply colour palettes / mix and match palettes

### ISSUE THREAD

**Issue by s-duffey** [gctools-outilsgc/design-system-code#134]
Even within our team, different designers tend to apply colours differently to our designs. Even though primary, secondary etc. is outlined in the CSS file, there is flexibility on where in the application to add certain colours. 

In the Colour documentation, provide a bit more context, and emphasize the ability to play with colour application.

**Comment by sabrinatbs** [comment]
To be reviewed and edited by @marianneaubrey15  next sprint

[Complementary_Palette_edited.txt](https://zube.io/files/tbs-sct/581262c0f89452085961993eb2914b55-complementary_palette_edited.txt)

**Comment by sabrinatbs** [comment]
![Colour-Palette.png](https://zube.io/files/tbs-sct/555fe9dcd8448745d667af0fad6565bc-colour-palette.png)

**Comment by s-duffey** [comment]
Text complete, will be edited and sent to translation before being added to repo.

**Comment by s-duffey** [comment]
A proposal for a new colour palette is a different task than documentation (which is complete), so I will close this card and create a new one for @sabrinatbs for next sprint.
