### ISSUE TITLE
FYI: Australia's design system

### ISSUE THREAD

**Issue by thomasgohard** [gctools-outilsgc/design-system-code#196]
Currently in beta: https://designsystem.gov.au/.

**Comment by s-duffey** [comment]
Thanks @thomasgohard! I think this was released at some point last year, we used it for reference a bit later into our project. Maybe eventually Canada.ca guidelines could look like this? ;) We're currently chatting with Canada.ca folks to see if there's a good way to better integrate their guidelines and the Aurora site
