### ISSUE TITLE
Evaluate current design system colours, propose different colour palettes

### ISSUE THREAD

**Issue by s-duffey** [gctools-outilsgc/design-system-code#198]
Evaluate currently colours used in the design system
-Play around with the colours
-What colours work with which emotions?

**Comment by sabrinatbs** [comment]
[Aurora Design System Colour Palettes.docx](https://zube.io/files/tbs-sct/cfba1d8cb25a13366e52c94ffe4a2968-aurora-design-system-colour-palettes.docx)

![Colour-Palette.png](https://zube.io/files/tbs-sct/1a313185322c7b467053f838d239afee-colour-palette.png)

![Colour-Palette_W Shades.png](https://zube.io/files/tbs-sct/c0d3d6cad785a2dc664eb8e71fbedda9-colour-palette_w-shades.png)

![Colour-Palettes_Gradients.png](https://zube.io/files/tbs-sct/0cadcc1feb64ac71193a174ed65ba071-colour-palettes_gradients.png)
