### ISSUE TITLE
Presentation for managers to approve final Aurora Borealis swatches and full palette

### ISSUE THREAD

**Issue by s-duffey** [gctools-outilsgc/design-system-code#205]
Modify colour presentation to present it to managers and Chris Jaja for approval. New presentation will include the following:
- [x] main 5 swatches for Aurora Borealis
- [x] full palette including text colours, lighter shades and darker shades built from 5 swatches
- [x] 3 gradient examples
- [x] examples of these 5 swatches being used in application designs

**Comment by sabrinatbs** [comment]
[Aurora Design System M-Presentation (1).pdf](https://zube.io/files/tbs-sct/13b1f60f9cbe1d45918c26247c53885b-aurora-design-system-m-presentation-1.pdf)
