### ISSUE TITLE
Guidance on curly quotes

### ISSUE THREAD

**Issue by jkshapiro** [gctools-outilsgc/design-system-code#227]
The "Quotation marks" section of https://design.gccollab.ca/content/formatting doesn't mention the distinction between straight and curly quotes. Should it?

I've found both in the documentation, so once a standard has been set it should be followed.

**Comment by s-duffey** [comment]
Hi @jkshapiro is there usually an understood difference between the two? If you could suggest something to add that would be great!

**Comment by jkshapiro** [comment]
Not really. It's basically just "always use curly quotes" or "always use straight quotes".

**Comment by jkshapiro** [comment]
Using <q> is a third option; thanks for mentioning it. I was referring to the insertion of actual straight quote and curly quote characters in the text. The French version of the page https://design.gccollab.ca/content/formatting, for instance, has straight quotes in the "Guillemets" section and curly quotes in the "Gras et italiques" section.
