### ISSUE TITLE
"Axes should always start at 0"

### ISSUE THREAD

**Issue by jkshapiro** [gctools-outilsgc/design-system-code#231]
The page https://design.gccollab.ca/data/data-overview specifies that on a graph, "axes should always start at 0". This seems unnecessarily limiting: some data is more clearly presented when axes don't start at zero. For instance, if an industrial process typically runs at 2300 degrees, with a tolerance of +/- 20 degrees, then it would be very hard to see values that were out of tolerance if your axis started all the way down at zero.

**Comment by jkshapiro** [comment]
Dates are a common example of data that should not start at zero.

**Comment by jkshapiro** [comment]
This guidance also occurs at https://design.gccollab.ca/data/scatterplots

**Comment by s-duffey** [comment]
Thanks @jkshapiro. We can take that phrase out if it makes sense!
