### ISSUE TITLE
"Round to two decimals if necessary"

### ISSUE THREAD

**Issue by jkshapiro** [gctools-outilsgc/design-system-code#233]
The page https://design.gccollab.ca/content/formatting includes the guidance, "round to two decimals if necessary". This seems pretty arbitrary. Gas prices and FM radio frequencies, for instance, are generally rounded to one decimal.

**Comment by jkshapiro** [comment]
So are the money examples at https://design.gccollab.ca/data/data-overview/

**Comment by s-duffey** [comment]
Thanks. Will make the change in next update.
