### ISSUE TITLE
Merge all relevant branches into the master

### ISSUE THREAD

**Issue by Addyvan** [gctools-outilsgc/design-system-code#43]
In order to migrate things into the gatsby v1 version that works with IE I need all the changes/branches to be added to the master. At the moment the master is not the deployable version found in the gh-pages branch. 

Current branches that need to be reviewed or finalized and submitted as pull requests:
- [x] final-style 
- [x] french-documentation
- [x] tables
- [x] jsxify-nav
- [x] dropdownButtonState
- [x] features (branch removed)

**Comment by s-duffey** [comment]
All branches merged.
