### ISSUE TITLE
Nav not completely accessible on mobile

### ISSUE THREAD

**Issue by s-duffey** [gctools-outilsgc/design-system-code#77]
_Originally created by Rick Massie on Sept. 25_

The NAV menu is missing the last menu item, but there is no indication to scroll left. A sighted user would have no idea it exists. It would be good to jump to a hamburger menu when the NAV expands beyond the device width.

![image](https://user-images.githubusercontent.com/31668114/47667857-6794cc80-db7d-11e8-9b61-99c414d87312.png)

Increase padding to make it cut off the screen.

**Comment by ethanWallace** [comment]
Closed with pull request #132
