### ISSUE TITLE
Anchor links and Menu Nav issue

### ISSUE THREAD

**Issue by s-duffey** [gctools-outilsgc/design-system-code#78]
_Originally created by Rick Massie on Sept. 18_

When creating an anchor link, the page jumps to the correct anchor.

However, the anchor ends up being hidden underneath the top nav menu. I'm not sure exactly what is happening, but somehow the Nav menu seems to be "floating" above the rest of the content, and since the browser bring anchor links to the top of the content area, it actually ends up hidden under the nav menu.

**Comment by ethanWallace** [comment]
Closed with pull request #132
